// The methods index: the forward map, docs/METHODS.md.
//
// Every method authors its identity in its own frontmatter (id, name, type,
// invented_by, source, prompts) under packages/khai-methods/methods/*.md. This
// module gathers those into a single generated `docs/METHODS.md`: navigate from
// a purpose (the type) to the methods that serve it, and from a method to its
// origin, so the registry is legible without opening every file.
//
// Computed, not hand-kept: the method frontmatter is the single source, so the
// index and the methods can never drift. `buildMethodsIndex` is the sole writer;
// `verifyMethodsIndex` is the drift gate (mirrors docs/SCIENCE.md's build-drift
// gate) — a stale or hand-edited index fails at the PR, not months later when
// the map is next consulted.
//
// The render is list-based on purpose: it stays byte-stable under Prettier (a
// padded table does not), so the committed index needs no prettier-ignore entry
// and the whole feature rides the one methods lane. The writer and the verifier
// are the one code path, dependency-free beyond the registry it already reads.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { listMethods } from "./index.mjs";

/** Where the generated index lives, relative to the repo root. */
export const METHODS_INDEX_PATH = "docs/METHODS.md";

// Escape a markdown link's text span. Backslash first (so the escape character
// itself is escaped, not left to bypass the rest), then the brackets that would
// otherwise close the span; the rest of the frontmatter renders verbatim.
const linkText = (s) =>
  String(s ?? "")
    .replace(/\\/g, "\\\\")
    .replace(/([[\]])/g, "\\$1");

/** The attribution names as one string: "Mary Gorman & Ellen Gottesdiener". */
function inventors(m) {
  const names = (m.invented_by ?? []).map((a) => a && a.name).filter(Boolean);
  if (names.length <= 1) return names[0] ?? "";
  return names.slice(0, -1).join(", ") + " & " + names[names.length - 1];
}

/** The origin phrase: who invented it, when, and the source (linked if it has a url). */
function origin(m) {
  const who = inventors(m);
  const lead = who + (m.year ? ` (${m.year})` : "");
  const title = m.source && m.source.title;
  const src = title
    ? m.source.url
      ? `[${linkText(title)}](${m.source.url})`
      : linkText(title)
    : "";
  if (lead && src) return `${lead}. ${src}`;
  return lead || src || "unattributed";
}

/** The prompt labels in order, middot-joined: "Emergent · Perverse · Irreducible". */
function promptLabels(m) {
  return (m.prompts ?? [])
    .map((p) => p.label || p.key)
    .filter(Boolean)
    .join(" · ");
}

/** One method as a list line, linking to its file. */
function methodLine(m) {
  const labels = promptLabels(m);
  const prompts = labels ? ` Prompts: ${labels}.` : "";
  return `- [**${linkText(m.name)}**](../packages/khai-methods/methods/${m.id}.md) (\`${m.id}\`): ${origin(m)}.${prompts}`;
}

/**
 * Render the registry into the generated markdown. Deterministic: stable sorts
 * only, list-based so Prettier leaves it byte-identical.
 */
export function renderMethodsIndex(methods) {
  const sorted = [...methods].sort((a, b) => a.id.localeCompare(b.id));
  const types = [...new Set(sorted.map((m) => m.type))].sort();

  const L = [];
  L.push("<!-- GENERATED by `khai-methods build` — DO NOT EDIT BY HAND. -->");
  L.push("<!-- Source of truth: each method's frontmatter in packages/khai-methods/methods/. -->");
  L.push("");
  L.push("# khai methods index");
  L.push("");
  L.push(
    `Every method khai packages, each attributed to its origin and ready to run. ` +
      `${sorted.length} methods across ${types.length} types. Built from each method's ` +
      `frontmatter, so the index and the methods cannot drift.`,
  );

  L.push("");
  L.push("## By type");
  for (const type of types) {
    const rows = sorted.filter((m) => m.type === type);
    L.push("");
    L.push(`### ${type} (${rows.length})`);
    L.push("");
    for (const m of rows) L.push(methodLine(m));
  }

  L.push("");
  L.push("## By origin");
  L.push("");
  const byInventor = new Map();
  for (const m of sorted)
    for (const a of m.invented_by ?? []) {
      const name = a && a.name;
      if (!name) continue;
      if (!byInventor.has(name)) byInventor.set(name, []);
      byInventor.get(name).push(m.id);
    }
  const names = [...byInventor.keys()].sort((a, b) =>
    a.toLowerCase().localeCompare(b.toLowerCase()),
  );
  for (const name of names) {
    const ids = byInventor.get(name).sort();
    L.push(`- **${linkText(name)}**: ${ids.map((id) => `\`${id}\``).join(", ")}`);
  }
  L.push("");
  return L.join("\n");
}

/** Build the index from the registry and write it. The single writer of the index. */
export function buildMethodsIndex(root) {
  const text = renderMethodsIndex(listMethods());
  writeFileSync(join(root, METHODS_INDEX_PATH), text);
  return text;
}

/**
 * The drift gate: the committed index must equal what the build produces from
 * the method frontmatter. Returns an array of error strings (empty when in sync),
 * mirroring the shape docs/SCIENCE.md's drift gate uses.
 */
export function verifyMethodsIndex(root) {
  const built = renderMethodsIndex(listMethods());
  const path = join(root, METHODS_INDEX_PATH);
  if (!existsSync(path)) return [`${METHODS_INDEX_PATH} is missing; run \`npm run build:methods\``];
  const committed = readFileSync(path, "utf8");
  if (committed !== built)
    return [`${METHODS_INDEX_PATH} is out of date; run \`npm run build:methods\``];
  return [];
}
