import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { mkdtempSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { renderPublication } from "../lib/publication.mjs";

let artifactDir;

beforeAll(() => {
  artifactDir = mkdtempSync(join(tmpdir(), "khai-pub-"));
  writeFileSync(join(artifactDir, "a.md"), "---\nkhai: note\n---\n\n# A\n\nalpha\n");
  writeFileSync(join(artifactDir, "b.md"), "# B\n\nbeta\n");
});

afterAll(() => rmSync(artifactDir, { recursive: true, force: true }));

describe("renderPublication", () => {
  it("combines collections into one markdown artifact (bundled/portable)", async () => {
    const pub = await renderPublication("markdown", {
      artifactDir,
      collections: { one: "a.md", two: "b.md" },
      injectMeta: false,
    });
    expect(pub.format).toBe("markdown");
    expect(pub.entries).toHaveLength(1);
    expect(pub.entries[0].path).toBe("markdown.md");
    expect(pub.entries[0].content).toContain("# A"); // frontmatter stripped
    expect(pub.entries[0].content).not.toContain("khai: note");
    expect(pub.entries[0].content).toContain("# B");
  });

  it("emits one artifact per collection for an expanded venue", async () => {
    const pub = await renderPublication("github_pages", {
      artifactDir,
      collections: { one: "a.md", two: "b.md" },
      format: "markdown",
      injectMeta: false,
    });
    const paths = pub.entries.map((e) => e.path).sort();
    expect(paths).toEqual(["one.md", "two.md"]);
  });

  it("injects the generated-by metadata block by default", async () => {
    const pub = await renderPublication("markdown", { artifactDir, collections: { one: "a.md" } });
    expect(pub.entries[0].content).toContain("Generated by khai-tour");
    expect(pub.entries[0].content).toContain("Profile: markdown");
  });

  it("rejects a format the venue does not support", async () => {
    await expect(
      renderPublication("print", {
        artifactDir,
        collections: { x: "a.md" },
        format: "html",
      }),
    ).rejects.toThrow("does not support format");
  });

  it("does not implement the pdf renderer yet", async () => {
    await expect(
      renderPublication("print", { artifactDir, collections: { x: "a.md" } }),
    ).rejects.toThrow("not implemented yet");
  });

  it("rejects an interactive venue", async () => {
    await expect(renderPublication("perplexity_space", { artifactDir })).rejects.toThrow(
      "not publication",
    );
  });
});
