#!/usr/bin/env node
// khai-review CLI. Runs the NLP-review lane an audit manifest declares, then
// reconciles the result against the audit's ledger (the collector) so a finding
// already known is not raised again. Emits: the ledger (the collector's memory),
// the log (human view), and the NEW findings as JSON (for a workflow to post as
// inline PR comments). Advisory: it ALWAYS exits 0; the audit PR's
// conversation-resolution rule is the gate, not CI.
//
//   khai-review --manifest audit/<id>/audit.json
//     [--ledger audit/<id>/ledger.json] [--log audit/<id>/log.md] [--new new.json]
//
// Defaults derive from the manifest's folder, so the common case is just
// `--manifest audit/<id>/audit.json`. The judge is the model-backed one
// (createModelJudge), configured from the environment (KHAI_REVIEW_TOKEN or
// GITHUB_TOKEN, KHAI_REVIEW_ENDPOINT, KHAI_REVIEW_MODEL). Set KHAI_REVIEW_MOCK=1
// for a local dry run with the deterministic mockJudge (wiring proof only).

import {
  readFileSync,
  existsSync,
  writeFileSync,
  statSync,
  appendFileSync,
  readdirSync,
} from "node:fs";
import { resolve, join, basename, dirname, relative } from "node:path";
import {
  reviewCard,
  reviewMarkdown,
  rubrics,
  resolvePositionRubrics,
  mockJudge,
  createModelJudge,
  collect,
  applyDecisions,
  commentBody,
  anchorLine,
  escapeCell,
} from "./index.mjs";

const argv = process.argv.slice(2);
const useMock = process.env.KHAI_REVIEW_MOCK === "1";

function flag(name) {
  const i = argv.indexOf(name);
  if (i === -1) return undefined;
  const v = argv[i + 1];
  return v && !v.startsWith("--") ? v : undefined;
}

/** Resolve a dir or package.json path to its `khai` manifest + engine slug. */
function engineAt(arg, root) {
  const p = resolve(root, arg);
  const pkgPath = existsSync(p) && statSync(p).isDirectory() ? join(p, "package.json") : p;
  if (!existsSync(pkgPath)) return null;
  let pkg;
  try {
    pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
  } catch {
    return null; // a malformed target manifest is skipped, not fatal (advisory lane)
  }
  if (!pkg.khai || !pkg.khai.card) return null;
  return {
    engine: pkg.khai.engine ?? basename(dirname(pkgPath)),
    manifest: pkg.khai,
    dir: dirname(pkgPath),
  };
}

// Returns `fallback` when the file is missing OR unreadable/malformed: a
// hand-edited ledger or decisions file must not crash the advisory lane.
const readJson = (p, fallback) => {
  if (!existsSync(p)) return fallback;
  try {
    return JSON.parse(readFileSync(p, "utf8"));
  } catch {
    return fallback;
  }
};

// Every `.md` under `dir` (recursive), so nested element files (e.g.
// plays/<id>/play_<id>.md, nested persona_*.md) are reviewed, not just the
// top-level ones. Skips node_modules and dot dirs, and the generated CHANGELOG.
// Sorted for deterministic review/log order.
function mdFilesUnder(dir) {
  const out = [];
  const entries = readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name),
  );
  for (const entry of entries) {
    if (entry.name.startsWith(".") || entry.name === "node_modules") continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...mdFilesUnder(full));
    else if (entry.name.endsWith(".md") && entry.name !== "CHANGELOG.md") out.push(full);
  }
  return out;
}

/** The audit log: a human view generated from the ledger. Never hand-edited. */
function renderLog(auditId, ledger) {
  const open = ledger.filter((e) => e.status === "open");
  const head = [
    `# Audit log: ${auditId}`,
    "",
    "_generated by khai-review from the ledger; status mirrors the audit PR. Do not hand-edit._",
    "",
  ];
  if (!ledger.length)
    return head.concat("No findings: every reviewed card reads lean.", "").join("\n") + "\n";
  // Shared with anchorLine so the rendered id cell and the anchor needle agree.
  const cell = escapeCell;
  const row = (e) =>
    `| \`${cell(e.id)}\` | ${cell(e.where)} | ${cell(e.reason)} | ${cell(e.treatment) || "—"} | ${cell(e.status)} | ${cell(e.resolution) || "—"} |`;
  return (
    head
      .concat(
        "| id | location | finding | treatment | status | resolution |",
        "| -- | -------- | ------- | --------- | ------ | ---------- |",
        ...ledger.map(row),
        "",
        `_${open.length} open of ${ledger.length} tracked._`,
        "",
      )
      .join("\n") + "\n"
  );
}

async function main() {
  const manifestPath = flag("--manifest");
  if (!manifestPath) {
    console.log("khai-review: --manifest <audit/<id>/audit.json> is required.");
    return;
  }
  const manifestAbs = resolve(manifestPath);
  const auditDir = dirname(manifestAbs);
  const repoRoot = process.cwd();
  // A missing or malformed manifest is config, not a build break: report and
  // exit 0, like the missing-token path below.
  let cfg;
  try {
    cfg = JSON.parse(readFileSync(manifestAbs, "utf8"));
  } catch (err) {
    console.log(`khai-review: cannot read manifest ${manifestPath} — ${err.message}`);
    return;
  }
  const auditId = cfg.id ?? basename(auditDir);
  const review = cfg.review ?? {};
  // The checks are what a house checks for, and they coexist: named rubrics the
  // manifest opts into (the voice case, or any extra lens) merged with the
  // rubrics resolved from the house's own management positions when the manifest
  // asks (`fromPositions`). No universal set is imposed; the count is the
  // house's. Back-compat: with neither, the historical conciseness default holds.
  const named = (review.rubrics ?? (review.fromPositions ? [] : ["conciseness"]))
    .map((id) => rubrics[id])
    .filter(Boolean);
  const positions = review.fromPositions
    ? resolvePositionRubrics(
        resolve(
          repoRoot,
          typeof review.fromPositions === "string"
            ? review.fromPositions
            : (review.management ?? "management"),
        ),
      )
    : [];
  const checks = [...named, ...positions];
  // The house's local robustness thresholds (n, k, skeptic): when present, every
  // rubric runs through the consensus/skeptic/anchor wrapper, so the audit does
  // not ride on one sample of one model. Absent, the review is single shot.
  const robust = review.thresholds ?? null;
  const targets = (review.targets ?? []).map((t) => engineAt(t, repoRoot)).filter(Boolean);

  const ledgerPath = resolve(flag("--ledger") ?? join(auditDir, "ledger.json"));
  const logPath = resolve(flag("--log") ?? join(auditDir, "log.md"));
  const newPath = flag("--new") ? resolve(flag("--new")) : null;

  if (!targets.length) {
    console.log(`khai-review[${auditId}]: no engine packages with a card to review.`);
    return;
  }
  // A missing token is config, not a build break: report and exit 0.
  if (!useMock && !(process.env.KHAI_REVIEW_TOKEN || process.env.GITHUB_TOKEN)) {
    console.log(
      `khai-review[${auditId}]: skipped, no token (set KHAI_REVIEW_TOKEN or GITHUB_TOKEN).`,
    );
    return;
  }
  const judge = useMock ? mockJudge : createModelJudge();

  // Run the review -> fresh findings, each with the stable, audit-scoped id.
  const fresh = [];
  for (const t of targets) {
    let flags = [];
    try {
      flags = await reviewCard(t.manifest, judge, checks, repoRoot, t.dir, robust);
      const files = mdFilesUnder(t.dir);
      for (const filePath of files) {
        // Label by path relative to the target dir, so a top-level file keeps
        // its bare name (stable id) and a nested one is disambiguated.
        const file = relative(t.dir, filePath);
        try {
          const text = readFileSync(filePath, "utf8");
          if (/^---\r?\n[\s\S]*?\bkhai:/.test(text)) {
            const relPath = relative(repoRoot, filePath);
            const mdFlags = await reviewMarkdown(
              file,
              text,
              judge,
              checks,
              repoRoot,
              relPath,
              robust,
            );
            flags.push(...mdFlags);
          }
        } catch (err) {
          flags.push({
            where: `${file} (failed)`,
            rubric: "n/a",
            reason: err.message,
            suggestion: null,
          });
        }
      }
    } catch (err) {
      flags = [{ where: "(review failed)", rubric: "n/a", reason: err.message, suggestion: null }];
    }
    for (const f of flags)
      fresh.push({ id: `${auditId}:${t.engine}:${f.where}:${f.rubric}`, engine: t.engine, ...f });
  }

  // The collector: dedup, carry treatments, and verify Reduce claims.
  const prior = readJson(ledgerPath, []);
  let { ledger, added, reopened } = collect(prior, fresh);

  // Sync the table from the PR's comment treatments (the comment -> table step),
  // so what a human decided in a thread is recorded in the ledger. The set of
  // ids the review still flags decides reduce-pending vs reduced.
  const decisions = flag("--decisions") ? readJson(resolve(flag("--decisions")), []) : [];
  if (decisions.length) ledger = applyDecisions(ledger, decisions, new Set(fresh.map((f) => f.id)));

  writeFileSync(ledgerPath, JSON.stringify(ledger, null, 2) + "\n");
  const log = renderLog(auditId, ledger);
  writeFileSync(logPath, log);
  // New findings, ready for the workflow to post as inline comments: each
  // carries the body (with the finding-id marker) and the log line to anchor to.
  if (newPath) {
    const logRel = relative(repoRoot, logPath);
    // Build the comment from the fresh finding (it carries `current`, the
    // original prose), not the ledger entry which does not store it.
    const freshById = new Map(fresh.map((f) => [f.id, f]));
    const comments = added.map((e) => ({
      id: e.id,
      path: logRel,
      line: anchorLine(log, e.id),
      body: commentBody(freshById.get(e.id) ?? e),
    }));
    writeFileSync(newPath, JSON.stringify(comments, null, 2) + "\n");
  }

  const open = ledger.filter((e) => e.status === "open").length;
  const pending = ledger.filter((e) => e.status === "reduce-pending").length;
  const summary = `khai-review[${auditId}]: ${added.length} new, ${reopened.length} regressed, ${pending} reduce-pending, ${open} open, ${ledger.length} tracked.\n`;
  process.stdout.write(summary + log);
  if (process.env.GITHUB_STEP_SUMMARY) appendFileSync(process.env.GITHUB_STEP_SUMMARY, log);
}

// Advisory lane: any unexpected error is reported but never gates (exit 0).
await main().catch((err) => {
  console.log(`khai-review: skipped (advisory) — ${err?.message ?? err}`);
});
