#!/usr/bin/env node
// khai-review CLI. Runs the NLP-review lane an audit manifest declares, then
// reconciles the result against the audit's ledger (the collector) so a finding
// already known is not raised again. Emits: the ledger (the collector's memory),
// the log (human view), and the NEW findings as JSON (for a workflow to post as
// inline PR comments). Advisory: it ALWAYS exits 0; the audit PR's
// conversation-resolution rule is the gate, not CI.
//
//   khai-review --manifest audit/<id>/audit.json
//     [--ledger audit/<id>/ledger.json] [--log audit/<id>/log.md] [--new new.json]
//
// Defaults derive from the manifest's folder, so the common case is just
// `--manifest audit/<id>/audit.json`. The judge is the model-backed one
// (createModelJudge), configured from the environment (KHAI_REVIEW_TOKEN or
// GITHUB_TOKEN, KHAI_REVIEW_ENDPOINT, KHAI_REVIEW_MODEL). Set KHAI_REVIEW_MOCK=1
// for a local dry run with the deterministic mockJudge (wiring proof only).

import { readFileSync, existsSync, writeFileSync, statSync, appendFileSync } from "node:fs";
import { resolve, join, basename, dirname, relative } from "node:path";
import {
  reviewCard,
  rubrics,
  mockJudge,
  createModelJudge,
  collect,
  commentBody,
  anchorLine,
} from "./index.mjs";

const argv = process.argv.slice(2);
const useMock = process.env.KHAI_REVIEW_MOCK === "1";

function flag(name) {
  const i = argv.indexOf(name);
  if (i === -1) return undefined;
  const v = argv[i + 1];
  return v && !v.startsWith("--") ? v : undefined;
}

/** Resolve a dir or package.json path to its `khai` manifest + engine slug. */
function engineAt(arg, root) {
  const p = resolve(root, arg);
  const pkgPath = existsSync(p) && statSync(p).isDirectory() ? join(p, "package.json") : p;
  if (!existsSync(pkgPath)) return null;
  const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
  if (!pkg.khai || !pkg.khai.card) return null;
  return { engine: pkg.khai.engine ?? basename(dirname(pkgPath)), manifest: pkg.khai };
}

const readJson = (p, fallback) => (existsSync(p) ? JSON.parse(readFileSync(p, "utf8")) : fallback);

/** The audit log: a human view generated from the ledger. Never hand-edited. */
function renderLog(auditId, ledger) {
  const open = ledger.filter((e) => e.status === "open");
  const head = [
    `# Audit log: ${auditId}`,
    "",
    "_generated by khai-review from the ledger; status mirrors the audit PR. Do not hand-edit._",
    "",
  ];
  if (!ledger.length)
    return head.concat("No findings: every reviewed card reads lean.", "").join("\n") + "\n";
  const row = (e) =>
    `| \`${e.id}\` | ${e.where ?? ""} | ${(e.reason ?? "").replace(/\|/g, "\\|")} | ${e.treatment ?? "—"} | ${e.status} | ${e.resolution ?? "—"} |`;
  return (
    head
      .concat(
        "| id | location | finding | treatment | status | resolution |",
        "| -- | -------- | ------- | --------- | ------ | ---------- |",
        ...ledger.map(row),
        "",
        `_${open.length} open of ${ledger.length} tracked._`,
        "",
      )
      .join("\n") + "\n"
  );
}

async function main() {
  const manifestPath = flag("--manifest");
  if (!manifestPath) {
    console.log("khai-review: --manifest <audit/<id>/audit.json> is required.");
    return;
  }
  const manifestAbs = resolve(manifestPath);
  const auditDir = dirname(manifestAbs);
  const repoRoot = process.cwd();
  const cfg = JSON.parse(readFileSync(manifestAbs, "utf8"));
  const auditId = cfg.id ?? basename(auditDir);
  const review = cfg.review ?? {};
  const checks = (review.rubrics ?? ["conciseness"]).map((id) => rubrics[id]).filter(Boolean);
  const targets = (review.targets ?? []).map((t) => engineAt(t, repoRoot)).filter(Boolean);

  const ledgerPath = resolve(flag("--ledger") ?? join(auditDir, "ledger.json"));
  const logPath = resolve(flag("--log") ?? join(auditDir, "log.md"));
  const newPath = flag("--new") ? resolve(flag("--new")) : null;

  if (!targets.length) {
    console.log(`khai-review[${auditId}]: no engine packages with a card to review.`);
    return;
  }
  // A missing token is config, not a build break: report and exit 0.
  if (!useMock && !(process.env.KHAI_REVIEW_TOKEN || process.env.GITHUB_TOKEN)) {
    console.log(
      `khai-review[${auditId}]: skipped, no token (set KHAI_REVIEW_TOKEN or GITHUB_TOKEN).`,
    );
    return;
  }
  const judge = useMock ? mockJudge : createModelJudge();

  // Run the review -> fresh findings, each with the stable, audit-scoped id.
  const fresh = [];
  for (const t of targets) {
    let flags = [];
    try {
      flags = await reviewCard(t.manifest, judge, checks);
    } catch (err) {
      flags = [{ where: "(review failed)", rubric: "n/a", reason: err.message, suggestion: null }];
    }
    for (const f of flags)
      fresh.push({ id: `${auditId}:${t.engine}:${f.where}:${f.rubric}`, engine: t.engine, ...f });
  }

  // The collector: dedup, carry treatments, and verify Reduce claims.
  const prior = readJson(ledgerPath, []);
  const { ledger, added, reopened } = collect(prior, fresh);

  writeFileSync(ledgerPath, JSON.stringify(ledger, null, 2) + "\n");
  const log = renderLog(auditId, ledger);
  writeFileSync(logPath, log);
  // New findings, ready for the workflow to post as inline comments: each
  // carries the body (with the finding-id marker) and the log line to anchor to.
  if (newPath) {
    const logRel = relative(repoRoot, logPath);
    const comments = added.map((f) => ({
      id: f.id,
      path: logRel,
      line: anchorLine(log, f.id),
      body: commentBody(f),
    }));
    writeFileSync(newPath, JSON.stringify(comments, null, 2) + "\n");
  }

  const open = ledger.filter((e) => e.status === "open").length;
  const pending = ledger.filter((e) => e.status === "reduce-pending").length;
  const summary = `khai-review[${auditId}]: ${added.length} new, ${reopened.length} regressed, ${pending} reduce-pending, ${open} open, ${ledger.length} tracked.\n`;
  process.stdout.write(summary + log);
  if (process.env.GITHUB_STEP_SUMMARY) appendFileSync(process.env.GITHUB_STEP_SUMMARY, log);
}

await main();
