/**
 * khai-tour aggregator: assemble collections from source artifacts
 * Handles glob matching, file ordering, frontmatter stripping, content combining
 */

import { readFileSync } from "fs";
import { glob } from "node:fs/promises";
import { join } from "path";

/**
 * Strip YAML frontmatter from markdown content
 * @param {string} content - Raw markdown content
 * @returns {string} Content without frontmatter
 */
export function stripFrontmatter(content) {
  // Match frontmatter: --- at start, then content, then --- on its own line.
  // Use [ \t]* (not \s*) before the newline: \s matches \n, so \s*\n is
  // ambiguous and backtracks (CodeQL polynomial-regex). CRLF-tolerant.
  if (/^---[ \t]*\r?\n/.test(content)) {
    content = content.replace(/^---[ \t]*\r?\n[\s\S]*?\r?\n---[ \t]*\r?\n(?:[ \t]*\r?\n)*/, "");
  }
  return content;
}

/**
 * Find files matching a collection pattern
 * @param {string} baseDir - Directory to search in
 * @param {string|string[]} patterns - Glob pattern(s) to match
 * @returns {Promise<string[]>} Sorted file paths
 */
export async function findFiles(baseDir, patterns) {
  const patternArray = Array.isArray(patterns) ? patterns : [patterns];
  const allFiles = new Set();

  for (const pattern of patternArray) {
    // Node's built-in glob (node:fs/promises) keeps khai-tour zero-dependency.
    // It yields paths relative to cwd, matching the join(baseDir, file) below.
    for await (const file of glob(pattern, { cwd: baseDir })) {
      allFiles.add(file);
    }
  }

  return Array.from(allFiles).sort();
}

/**
 * Load and combine markdown files for a collection
 * @param {string} baseDir - Directory containing files
 * @param {string|string[]} patterns - Glob pattern(s) for collection
 * @param {boolean} stripFm - Whether to strip frontmatter (default: true)
 * @returns {Promise<string>} Combined markdown content
 */
export async function aggregateCollection(baseDir, patterns, stripFm = true) {
  const files = await findFiles(baseDir, patterns);

  if (files.length === 0) {
    throw new Error(`No files found matching patterns: ${JSON.stringify(patterns)}`);
  }

  const contents = [];

  for (const file of files) {
    const fullPath = join(baseDir, file);
    let content = readFileSync(fullPath, "utf-8");

    if (stripFm) {
      content = stripFrontmatter(content);
    }

    contents.push(content.trim());
  }

  // Join with page breaks (markdown horizontal rule)
  return contents.join("\n\n---\n\n");
}

/**
 * Aggregate multiple named collections
 * @param {string} baseDir - Base directory
 * @param {Object} collections - Map of collection name to pattern(s)
 * @param {boolean} stripFm - Strip frontmatter
 * @returns {Promise<Object>} Map of collection name to aggregated content
 */
export async function aggregateCollections(baseDir, collections, stripFm = true) {
  const results = {};

  for (const [name, patterns] of Object.entries(collections)) {
    try {
      results[name] = await aggregateCollection(baseDir, patterns, stripFm);
    } catch (err) {
      throw new Error(`Failed to aggregate collection "${name}": ${err.message}`);
    }
  }

  return results;
}

/**
 * Combine aggregated collections for bundled output
 * @param {Object} aggregatedCollections - Map from aggregateCollections
 * @param {string[]} collectionOrder - Optional order to combine in
 * @returns {string} Combined markdown for all collections
 */
export function combineCollections(aggregatedCollections, collectionOrder = null) {
  let order = collectionOrder || Object.keys(aggregatedCollections);
  const combined = [];

  for (const name of order) {
    const content = aggregatedCollections[name];
    if (!content) {
      console.warn(`Collection "${name}" not found in aggregated content`);
      continue;
    }
    combined.push(content);
  }

  // Join with prominent separators
  return combined.join("\n\n---\n\n");
}

/**
 * Metadata injection: add collection info to markdown
 * @param {string} content - Markdown content
 * @param {Object} metadata - Metadata to inject
 * @returns {string} Content with metadata block
 */
export function injectMetadata(content, metadata) {
  const meta = {
    timestamp: new Date().toISOString(),
    ...metadata,
  };

  const block = `<!-- Generated by khai-tour
  Profile: ${meta.profile || "unknown"}
  Timestamp: ${meta.timestamp}
  -->

`;

  return block + content;
}
